version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    assignees:
      - "dependabot"
    target-branch: "develop"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
