version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/Sao_Paulo"
    target-branch: "develop"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
